---
app_repo: https://github.com/GSA/catalog.data.gov
catalog_ckan_app_version: master

catalog_ckan_apache_server_name: "{{ catalog_host_public_next }}"
catalog_ckan_db_host: "{{ catalog_next_ckan_db_replica_host }}"
catalog_ckan_db_name: "{{ catalog_next_ckan_db_name }}"
catalog_ckan_db_pass: "{{ catalog_next_ckan_db_pass }}"
catalog_ckan_db_user: "{{ catalog_next_ckan_db_user }}"
catalog_ckan_plugins_default: "{{ catalog_next_ckan_plugins_default }}"

catalog_ckan_readwrite_configuration: readonly
catalog_ckan_redis_host: "{{ catalog_next_ckan_redis_host }}"
catalog_ckan_redis_password: "{{ catalog_next_ckan_redis_password }}"
catalog_ckan_redis_url: "{{ catalog_next_ckan_redis_url }}"
catalog_ckan_service_url: https://{{ catalog_host_public_next }}
catalog_ckan_admin_service_url: https://{{ catalog_host_admin_next }}
catalog_ckan_saml2_enabled: true
catalog_ckan_saml2_requested_authn_context:
  - http://idmanagement.gov/ns/assurance/aal/3?hspd12=true
catalog_ckan_solr_host: "{{ catalog_next_ckan_solr_a_host }}"  # default. this is probably overridden in other groups/host vars
catalog_ckan_who_ini_secret: "{{ catalog_next_ckan_who_ini_secret }}"

catalog_db_name: "{{ catalog_ckan_db_name }}"
catalog_db_pass: "{{ catalog_ckan_db_pass }}"
catalog_db_user: "{{ catalog_ckan_db_user }}"

ckan_catalog_next: true
ckan_instance_secret: "{{ catalog_next_ckan_instance_secret }}"
ckan_instance_uuid: "{{ catalog_next_ckan_instance_uuid }}"
ckan_production_ini_template: "{{ catalog_next_ckan_production_ini_template }}"
ckan_session_store_type: memory
ckan_site_domain: https://catalog-next-datagov.dev-ocsit.bsp.gsa.gov
ckan_uses_gunicorn: true
catalog_ckan_cache_control_max_age: 86400

datagov_service: catalog-next

newrelic_app_name: catalog-next

# Token for working with the Google Analytics API
token_dat: "{{ catalog_next_ckan_token_dat }}"

url_readonly: https://{{ catalog_host_public_next }}
url_writable: https://{{ catalog_host_admin_next }}

catalog_ckan_plugins_additional: [saml2auth]

# login.gov identity sandbox
saml2_idp_metadata_url: "https://idp.int.identitysandbox.gov/api/saml/metadata2020"
catalog_ckan_saml2_entity_id: urn:gov:gsa:SAML:2.0.profiles:sp:sso:gsa:datagov-staging-catalog
saml2_site_url: "https://admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov/"
saml2_idp_url: https://idp.int.identitysandbox.gov/api/saml/auth2020
saml2_sp_private_key: "{{ catalog_next_saml2_sp_private_key }}"
saml2_sp_public_certificate: "{{ catalog_next_saml2_sp_public_certificate }}"
saml2_idp_entry: idp.int.identitysandbox.gov
