---
# catalog
catalog_ckan_app_version: master
catalog_ckan_archiver_process_count: 3
catalog_ckan_db_host: "{{ vault_catalog_ckan_db_host }}"
catalog_ckan_db_name: "{{ vault_catalog_ckan_db_name }}"
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: "{{ vault_catalog_ckan_db_user }}"
catalog_ckan_email_from: "{{ default_email_from }}"
catalog_ckan_harvest_fetch_process_count: 6
catalog_ckan_plugins_additional: [saml2]
catalog_ckan_qa_update_process_count: 5
catalog_ckan_readwrite_configuration: readonly
catalog_ckan_redis_host: catalog-harvester1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_redis_password: "{{ redis_password }}"
catalog_ckan_fgdc2iso_host: catalog-fgdc2iso1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_saml2_enabled: true
catalog_ckan_who_ini_path: "etc_ckan_who.saml2.ini.j2"
catalog_ckan_service_url: https://catalog.data.gov
catalog_ckan_solr_port: "8983"
catalog_ckan_solr_host: datagov-solr1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_wsgi_processes: 6
catalog_pycsw_db_host: "{{ vault_catalog_pycsw_db_host }}"
catalog_pycsw_db_name: "{{ vault_catalog_pycsw_db_name }}"
catalog_pycsw_db_pass: "{{ vault_catalog_pycsw_db_pass }}"
catalog_pycsw_db_user: "{{ vault_catalog_pycsw_db_user }}"


# common
common_audit_report_enabled: false
common_filebeat_logstash_output: "{{ vault_common_filebeat_logstash_output }}"
common_filebeat_config:
  filebeat.config.modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
  filebeat.modules:
    - module: system
      syslog:
        enabled: true
  output.logstash:
    hosts: ["{{ common_filebeat_logstash_output }}"]

common_newrelic_enabled: "{{ datagov_in_service | default(true) }}"
common_python_version_number: 2.7.10
common_ubuntu_advantage_token: "{{ vault_common_ubuntu_advantage_token }}"
filebeat_enabled: true
nessus_agent_enabled: true
trendmicro_enabled: true
# TODO prefix these with common_
filebeat_config: "{{ common_filebeat_config }}"
products:
  - filebeat


# dashboard
# hostname needed for smoke test, IP address needed for ALB health check
dashboard_nginx_server_name: labs.data.gov labs-bsp.data.gov dashboard-bsp.data.gov $hostname {{ ansible_default_ipv4.address }}
dashboard_service_url: https://labs.data.gov/dashboard
php_cli_memory_limit: 3192M

# data.gov-wide variables
datagov_environment: production


default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIILLjCCChagAwIBAgITHQABMUAaEOFwb5JbWwACAAExQDANBgkqhkiG9w0BAQsF
  ADBvMRMwEQYKCZImiZPyLGQBGRYDZ292MRMwEQYKCZImiZPyLGQBGRYDZ3NhMRIw
  EAYKCZImiZPyLGQBGRYCZHMxEzARBgoJkiaJk/IsZAEZFgNlbnQxGjAYBgNVBAMT
  EUVDT0gyUy1JU1NDQTAxKDEpMB4XDTIwMDcyMjE5MjUyM1oXDTIyMTAyNTE5MjUy
  M1owge8xCzAJBgNVBAYTAlVTMR0wGwYDVQQIExREaXN0cmljdCBvZiBDb2x1bWJp
  YTETMBEGA1UEBxMKV2FzaGluZ3RvbjEoMCYGA1UEChMfR2VuZXJhbCBTZXJ2aWNl
  cyBBZG1pbmlzdHJhdGlvbjEqMCgGA1UECxMhVGVjaG5vbG9neSBUcmFuc2Zvcm1h
  dGlvbiBTZXJ2aWNlMTIwMAYDVQQDEyljYXRhbG9nLWZnZGMyaXNvMXAucHJvZC1v
  Y3NpdC5ic3AuZ3NhLmdvdjEiMCAGCSqGSIb3DQEJARYTZGF0YWdvdmhlbHBAZ3Nh
  LmdvdjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMf5XOHyjy3ovvKG
  DrxmrB4jimHrz/DNzwppG0NDZTRY4tArEb7lK3wbng/xgCJCe8jYHd0lTOjxTtQB
  EUx8c2O06ZV2yTIMAK0eWeV22yJwhenwTmBiZFFEl6/64WZPX67pXzGXAlgfNYIV
  yR8+J0LWb5mTC2YpRz2o8AvI8DG2HKyyfauRz55E2dMczNtNk4/9cpRTaWhUIIaw
  NlSqELsoCySODNzYFW2/k51A8cRkmZpwR0afAjs3ZKNb0/9OS8fRQtp/EGpcMr5P
  GRlFJF459PgopwUfUQ33rL/T7QnBp9b9Z8dt0WSAmYsnRYdrlebRCI2mfPoyQFwR
  9P/f/JUCAwEAAaOCB0Awggc8MBMGA1UdJQQMMAoGCCsGAQUFBwMBMIIFgwYDVR0R
  BIIFejCCBXaCKmNhdGFsb2ctaGFydmVzdGVyMXAucHJvZC1vY3NpdC5ic3AuZ3Nh
  LmdvdoIqY2F0YWxvZy1oYXJ2ZXN0ZXIycC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292
  gipjYXRhbG9nLWhhcnZlc3RlcjNwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCKmNh
  dGFsb2ctaGFydmVzdGVyNHAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIqY2F0YWxv
  Zy1oYXJ2ZXN0ZXI1cC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292gipjYXRhbG9nLWhh
  cnZlc3RlcjZwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJGNhdGFsb2ctd2ViMXAu
  cHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIkY2F0YWxvZy13ZWIycC5wcm9kLW9jc2l0
  LmJzcC5nc2EuZ292giVjYXRhbG9nYi13ZWIxcC5wcm9kLW9jc2l0LmJzcC5nc2Eu
  Z292giVjYXRhbG9nYi13ZWIycC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giRjYXRh
  bG9nYndlYjFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJGNhdGFsb2did2ViMnAu
  cHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIpY2F0YWxvZ2hhcnZlc3RlcjFwLnByb2Qt
  b2NzaXQuYnNwLmdzYS5nb3aCKWNhdGFsb2doYXJ2ZXN0ZXIycC5wcm9kLW9jc2l0
  LmJzcC5nc2EuZ292giljYXRhbG9naGFydmVzdGVyM3AucHJvZC1vY3NpdC5ic3Au
  Z3NhLmdvdoIpY2F0YWxvZ2hhcnZlc3RlcjRwLnByb2Qtb2NzaXQuYnNwLmdzYS5n
  b3aCKWNhdGFsb2doYXJ2ZXN0ZXI1cC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292gilj
  YXRhbG9naGFydmVzdGVyNnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoInY2F0YWxv
  Z3B1Yi13ZWIxcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giZjYXRhbG9ncHVid2Vi
  MXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIjY2F0YWxvZ3dlYjFwLnByb2Qtb2Nz
  aXQuYnNwLmdzYS5nb3aCI2NhdGFsb2d3ZWIycC5wcm9kLW9jc2l0LmJzcC5nc2Eu
  Z292giVkYXNoYm9hcmR3ZWIxcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giVkYXNo
  Ym9hcmR3ZWIycC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giVkYXRhZ292LWp1bXAy
  cC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giVkYXRhZ292LXNvbHIxcC5wcm9kLW9j
  c2l0LmJzcC5nc2EuZ292giVkYXRhZ292LXNvbHIycC5wcm9kLW9jc2l0LmJzcC5n
  c2EuZ292giZkYXRhZ292LXNvbHJtMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIj
  aW52ZW50b3J5LTFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCI2ludmVudG9yeS0y
  cC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giJpbnZlbnRvcnkxcC5wcm9kLW9jc2l0
  LmJzcC5nc2EuZ292giJpbnZlbnRvcnkycC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292
  gh5yZWRpczFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJXdvcmRwcmVzc3dlYjFw
  LnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJXdvcmRwcmVzc3dlYjJwLnByb2Qtb2Nz
  aXQuYnNwLmdzYS5nb3YwHQYDVR0OBBYEFJdtcOtqexvoYlauMZIgXRGDubU8MB8G
  A1UdIwQYMBaAFElMyfD/ZIWax2Ir/ssotChMRSIYMEwGA1UdHwRFMEMwQaA/oD2G
  O2h0dHA6Ly9nc2Fwa2kuZW50LmRzLmdzYS5nb3YvZ3NhY2VydHMvRUNPSDJTLUlT
  U0NBMDEoMikuY3JsMIGnBggrBgEFBQcBAQSBmjCBlzBlBggrBgEFBQcwAoZZaHR0
  cDovL2dzYXBraS5lbnQuZHMuZ3NhLmdvdi9nc2FjZXJ0cy9FQ09IMlMtSVNTQ0Ew
  MS5lbnQuZHMuZ3NhLmdvdl9FQ09IMlMtSVNTQ0EwMSgyKS5jcnQwLgYIKwYBBQUH
  MAGGImh0dHA6Ly9nc2FvY3NwLmVudC5kcy5nc2EuZ292L29jc3AwCwYDVR0PBAQD
  AgWgMDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQBgjcVCIOJry+FnqB9gvmDD4awjg2E
  n5cRPoHqnDWE72YCAWQCARMwGwYJKwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDATAN
  BgkqhkiG9w0BAQsFAAOCAQEAEbDqp2nOybZEDLtmV+qYi5IE284ch5tYiF9fRHJ4
  /1BRjc2j+MAU9jG6A/WRJDS/vBOsFrwE9vOUG3FBXEaS0g3sOClt/2XCEs3u9zDT
  E17vaZEsShI6/53vQPaRHqrs8YpYORzg6lzBXKBZAHXkZgiOyaJ6ZboG0Lsq0WS5
  8jb9XlCEw4Q59tWKFKVv4GOhsQBfWaBex/c3QXFIIXGAZbTOZJFdUf1suybSPq2Q
  IhpRD9pKeSJGCQ2fhlgTtR6jTDwM2gUhc83ECZ4sXLEkaLwfLIFFzHS5d1BZlMEm
  /Rre1TZ99ZG1rZEO5FO7Y5EPUy7k7qAKfJ5un+ToPZA4Qw==
  -----END CERTIFICATE-----


jumpbox_operators: "{{ datagov_operators_production }}"


inventory_ckan_service_url: https://inventory.data.gov
inventory_ckan_solr_host: datagov-solrm1p.prod-ocsit.bsp.gsa.gov
inventory_ckan_solr_port: "8983"


# New Relic
newrelic_license_key: "{{ vault_newrelic_license_key }}"


pycsw_app_version: datagov/v2.4.x
pycsw_base_url: https://catalog.data.gov
pycsw_ckan_url: https://catalog.data.gov
pycsw_db_host: "{{ catalog_pycsw_db_host }}"
pycsw_db_name: "{{ catalog_pycsw_db_name }}"
pycsw_db_password: "{{ catalog_pycsw_db_pass }}"
pycsw_db_user: "{{ catalog_pycsw_db_user }}"

# public urls
urls_public:
  catalog: https://catalog.data.gov
urls_private:
  catalog: "{{ vault_urls_private_catalog }}"
ckan_site_domain: "{{ urls_public.catalog }}"

# s3 bucket
catalog_bucket_name: "{{ vault_catalog_bucket_name }}"


# solr
solr_master_server: datagovsolrm1p.prod-ocsit.bsp.gsa.gov
solr_java_packages:
  - openjdk-8-jdk
solr_cores:
  - catalog
  - inventory
solr_xms: 8192m
solr_xmx: 8192m



# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"

# TrendMicro
trendmicro_deb_url: https://dsm.sec.helix.gsa.gov/software/agent/Ubuntu_14.04/x86_64/
trendmicro_policy_id_app: "{{ vault_trendmicro_policy_id_app }}"
trendmicro_policy_id_jumpbox: "{{ vault_trendmicro_policy_id_jumpbox }}"
trendmicro_policy_id_web: "{{ vault_trendmicro_policy_id_web }}"

# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"

# App environment
web_app_env: production
real_ansible_env: production

# postfix
default_email_from: "{{ vault_default_email_from }}"
postfix_raw_options:
  - |
    smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
    smtpd_tls_mandatory_ciphers = high
    smtpd_tls_mandatory_exclude_ciphers = aNULL, MD5
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_relaytls: true
postfix_sasl_auth_enable: false
postfix_smtpd_tls_cert_file: /etc/ssl/certs/datagov_host.crt
postfix_smtpd_tls_key_file: /etc/ssl/certs/datagov_host.key
postfix_aliases:
  - user: postmaster
    alias: root
  - user: root
    alias: "{{ datagov_team_email }}"
postfix_sender_canonical_maps:
  - sender: "@{{ ansible_fqdn }}"
    rewrite: no-reply+{{ ansible_fqdn }}@data.gov


# Redis
redis_password: "{{ vault_redis_password }}"


# SAML
saml2_idp_entry: login.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "67:76:BB:87:FE:76:D6:4A:BE:19:3F:E2:B6:1A:49:06:AE:56:06:B8"
saml2_sp_public_certificate: "{{ vault_saml2_sp_public_certificate }}"
saml2_sp_private_key: "{{ vault_saml2_sp_private_key }}"

# td-agent
elasticsearch_endpoint: "{{ vault_elasticsearch_endpoint }}"
bsp_elasticsearch_endpoint: "{{ vault_bsp_elasticsearch_endpoint }}"
bsp_shared_key: "{{ vault_bsp_shared_key }}"
system: "es"

# nessus
nessus_agent_key: "{{ vault_nessus_agent_key }}"
nessus_agent_host: "{{ vault_nessus_agent_host }}"
nessus_agent_port: "{{ vault_nessus_agent_port }}"
nessus_agent_group: "{{ vault_nessus_agent_group }}"

# saxon license
fgdc2iso_saxon_license: "{{ vault_fgdc2iso_saxon_license }}"


# ckan
# Auth cookie `auth_tkt` must be HTTPS-only (SECURE) on Production
who_secure: True

# Automated CI tests
ci_inventory: inventories/production
ci_ssh_config_host: '*.prod-ocsit.bsp.gsa.gov'
ci_deploy_version: master


# wordpress
# hostname needed for smoke test, IP address needed for ALB health check
wordpress_nginx_server_name: www.data.gov data.gov wp-bsp.data.gov labs.data.gov $hostname {{ ansible_default_ipv4.address }}
wordpress_service_url: https://www.data.gov
